### ISSUE TITLE
HOME not set for notebook image running on CLI

### ISSUE THREAD

**Issue by tiansiyuan** [vmware/vSphere-machine-learning-extension#133]
### Describe the bug

```sh
$ cd
bash: cd: HOME not set
```

### Reproduction steps

1. docker run -it kubeflownotebookswg/jupyter-pytorch-cuda-full /bin/bash
2.
3.
...

### Expected behavior

cd into HOME dir

**Comment by tiansiyuan** [comment]
```sh
$ python train.py --epoch 3           
github: skipping check (not a git repository)
Traceback (most recent call last):
  File "/home/jovyan/sh-power/notebook/train.py", line 522, in <module>
    device = select_device(opt.device, batch_size=opt.batch_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/sh-power/notebook/utils/torch_utils.py", line 71, in select_device
    assert torch.cuda.is_available(), f'CUDA unavailable, invalid device {device} requested'  # check availability
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: CUDA unavailable, invalid device 0 requested
```
